CREATE TABLE IF NOT EXISTS `Food_Store`.`PrimarySales` (
  `TimeID` VARCHAR(45) NOT NULL,
  `LocationID` VARCHAR(45) NOT NULL,
  `StaffID` VARCHAR(45) NOT NULL,
  `SalesID` VARCHAR(45) NOT NULL,
  `ItemsID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TimeID`),
  CONSTRAINT `LocationID`
    FOREIGN KEY ()
    REFERENCES `Food_Store`.`Location` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TimeID`
    FOREIGN KEY ()
    REFERENCES `Food_Store`.`Time` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StaffID`
    FOREIGN KEY ()
    REFERENCES `Food_Store`.`Staff` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SalesID`
    FOREIGN KEY ()
    REFERENCES `Food_Store`.`Sales` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ItemsID`
    FOREIGN KEY ()
    REFERENCES `Food_Store`.`Items` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB